### ISSUE TITLE
Circular Dependencies

### ISSUE THREAD

**Issue by Snickdx** [uwidcit/pharm-backend#1]
https://github.com/uwidcit/pharm-backend/blob/ecb5bfe69e2c05c80774a73e52f45a7e023bf1dc/App/models/invoice.py#L1

Because the __init__.py file of every MVC module depends on the MVC files you can't have your model files import from the __init__.py file. Instead, db should be imported from FlaskSqlAchemy.

**Comment by KCarlton96** [comment]
I had the db import in the init.py file that's why I'm referencing it. In the case of importing the db from FlaskSqlAlchemy, will I have to do that in each model? 
 
Also, should I be working in the main branch or in my own branch and only add the changes to main once functional?

**Comment by KCarlton96** [comment]
I believe I've fixed the circular dependency but am unable to run the application in gitpod. See screenshot below:
![gitpod error](https://user-images.githubusercontent.com/37227478/100189003-cf838180-2ec1-11eb-83d3-a220c4478e8a.png)

When I created a clone of main a few days ago for me to work on, the enviroment files were there.
Should I copy them over or were they removed to be fixed?

The way inheritance is implemented may have to be revisited, will work on it.
I've pushed all the changes I've made to the main branch so you can review them.

**Comment by KCarlton96** [comment]
Circular dependency fixed, app is running, connecting to db and creating models, changes to do this pushed to main
